reflog

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -67,7 +67,7 @@ jobs:
             **/target/site
 
   sonar:
-    name: 🔍 SonarQube Analysis
+    name: 🔍 SonarCloud Analysis
     runs-on: ubuntu-latest
     needs: test
     steps:
@@ -90,12 +90,17 @@ jobs:
       - name: Run SonarQube Analysis
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Nahima697_Elec_business_spring
+        run: |
+          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
+            -Dsonar.projectKey=nahima-toumi697_Elec_business_spring \
+            -Dsonar.organization=nahima-toumi697 \
+            -Dsonar.host.url=https://sonarcloud.io \
+            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
 
   build:
     name: 🚀 Build & Deploy
     runs-on: ubuntu-latest
-    needs: test
+    needs: [test, sonar]
     services:
       docker:
         image: docker:20.10.16-dind
@@ -119,6 +124,7 @@ jobs:
       URL_FRONT: ${{ secrets.URL_FRONT }}
       DOCKER_HOST: tcp://localhost:2375
       DOCKER_TLS_CERTDIR: ""
+      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
 
     steps:
       - name: 📥 Checkout du code
@@ -140,6 +146,21 @@ jobs:
             echo "ERROR: RENDER_API_KEY n'est pas défini !"
             exit 1
           fi
+          if [ -z "${{ secrets.SENDGRID_API_KEY }}" ]; then
+            echo "ERROR: SENDGRID_API_KEY n'est pas défini !"
+            exit 1
+          fi
 
       - name: Build Docker image
         run: docker build -t myapp --target prod .
+
+      - name: Deploy to Render
+        run: |
+          curl --request POST \
+            --url https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
+            --header 'accept: application/json' \
+            --header "authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
+            --header 'content-type: application/json' \
+            --data '{
+              "clearCache": "do_not_clear"
+            }'
